#TODO: REMINDERS:
# see if can find python3 image so dont have to install as much stuff
# apt install -y python3-pip && pip3 install -r requirements.txt

ENV FLASK_PORT=3000
ENV FLASK_HOST=0.0.0.0
ENV MINIO_HOST=minio
ENV MINIO_PORT=9000
ENV MINIO_ACCESS_KEY=minioUser
ENV MINIO_SECRET_KEY=minioPass
ENV MINIO_BUCKET=petorpass
